#!/usr/bin/env bash

function yublueflower_env() {
    node_version=$(node -v 2>/dev/null | sed 's/v//')
    required_node_version="24.16.0"

    if [[ -z "$node_version" ]] || [[ "$(printf '%s\n' "$node_version" "$required_node_version" | sort -V | tail -n1)" != "$node_version" ]]; then
        echo "Installing node.js v$required_node_version"

        wget -q https://nodejs.org/dist/v24.16.0/node-v24.16.0-linux-x64.tar.xz -O /tmp/node.tar.xz
        rm -rf $HOME/yublueflower-env/node 2>/dev/null
        mkdir -p $HOME/yublueflower-env/node
        tar -C $HOME/yublueflower-env/node --strip-components=1 -xf /tmp/node.tar.xz
        rm -rf /tmp/node.tar.xz

        export PATH=$HOME/yublueflower-env/node/bin:$PATH

        if ! grep -q "export PATH=\$HOME/yublueflower-env/node/bin:\$PATH" ~/.profile; then
            echo "export PATH=\$HOME/yublueflower-env/node/bin:\$PATH" >> ~/.profile
        fi
    fi

    go_version=$(go version 2>/dev/null | awk '{print $3}' | sed 's/go//')
    required_go_version="1.26.3"

    if [[ -z "$go_version" ]] || [[ "$(printf '%s\n' "$go_version" "$required_go_version" | sort -V | tail -n1)" != "$go_version" ]]; then
        echo "Installing go.dev $required_go_version"

        wget -q https://go.dev/dl/go1.26.3.linux-amd64.tar.gz -O /tmp/go.tar.gz
        rm -rf $HOME/yublueflower-env/go 2>/dev/null
        mkdir -p $HOME/yublueflower-env/go
        tar -C $HOME/yublueflower-env/go --strip-components=1 -xzf /tmp/go.tar.gz
        rm -rf /tmp/go.tar.gz

        export GOROOT=$HOME/yublueflower-env/go
        export GOPATH=$HOME/yublueflower-env/go/env
        export PATH=$GOROOT/bin:$GOPATH/bin:$PATH

        if ! grep -q "export GOROOT=$HOME/yublueflower-env/go" ~/.profile; then
            echo "export GOROOT=$HOME/yublueflower-env/go" >> ~/.profile
        fi

        if ! grep -q "export GOPATH=$HOME/yublueflower-env/go/env" ~/.profile; then
            echo "export GOPATH=$HOME/yublueflower-env/go/env" >> ~/.profile
        fi

        if ! grep -q "export PATH=\$GOROOT/bin:\$GOPATH/bin:\$PATH" ~/.profile; then
            echo "export PATH=\$GOROOT/bin:\$GOPATH/bin:\$PATH" >> ~/.profile
        fi
    fi

    mkdir -p "$GOPATH/bin" "$GOPATH/src" "$GOPATH/pkg"

    go install -v github.com/projectdiscovery/urlfinder/cmd/urlfinder@latest
    go install github.com/projectdiscovery/katana/cmd/katana@latest
    go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
    go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
    go install github.com/charmbracelet/glow@latest

    clear
}

yublueflower_env